version: "3.7"

services:
  qiitime:
    container_name: qiitime
    build: .
    image: qiitime
    volumes:
      # Uncomment below to edit script realtime
      #- ./src/:/app/
      - ./data/:/data/
    env_file: mastodon.env
