sut:
  build: .
  # run test file inside a container using the built image
  volumes:
    - ./run-test.sh:/app/run-test.sh
  environment:
    - MSTDN_ACCESSTOKEN
    - IS_MODE_DEBUG='true'
    - MSTDN_TOOT_MAIN='This is a sample toot'
    - MSTDN_TOOT_SPOILER='%%DATE_TIME%%'
  entrypoint: /app/run-test.sh
